// ... other imports and code ...

const productSchema = z.object({
  // ... other fields ...
  address: z.object({
    // ... other address fields ...
    country: z.string().default("India"),
    state: z.string().min(1, "State is required"),
    pincode: z.string().length(6, "PIN code must be 6 digits").regex(/^[0-9]+$/, "Must be a valid PIN code"),
    // ... other address fields ...
  }),
  // ... other fields ...
});


// ... rest of the code ...